# Full configuration reference: https://symfony.com/bundles/ux-icons/current/index.html#configuration
ux_icons:

    icon_sets:
        custom:
            path: '%kernel.project_dir%/assets/icons'

    # The local directory where icons are stored
    icon_dir: '%kernel.project_dir%/assets/icons'

    # Default HTML attributes to add to all icons
    default_icon_attributes:

        # Use current text color to fill the icon
        fill: currentColor

        # Default dimensions
        height: '1em'
        width: '1em'

    # Throw an exception if an icon is not
    ignore_not_found: false

when@prod:
    ux_icons:
        # Suppress exceptions for missing icons in production
        ignore_not_found: true
